font:
  normal:
    family: Cascadia Code
    style: Regular
  size: 14

window:
    dimensions:
        columns: 80
        lines: 24
    opacity: 0.85

colors:
    primary:
        background: '#000020'
        foreground: '#c8c8ff'
    normal:
        black: '#000000'
        red: '#aa0000'
        green: '#00aa00'
        yellow: '#aa5500'
        blue: '#0000aa'
        magenta: '#aa00aa'
        cyan: '#00aaaa'
        white: '#aaaaaa'
    bright:
        black: '#555555'
        red: '#ff5555'
        green: '#55ff55'
        yellow: '#ffff55'
        blue: '#5555ff'
        magenta: '#ff55ff'
        cyan: '#55ffff'
        white: '#ffffff'
